discovery_mode:
  type: string
  default: category
  description:
    en: . Specify which taxonomy should be used to enable the Kanban Board view. Options - category/tag. Use @ for both.
display_list:
  type: list
  default: ""
  description:
    en: A list of categories or tags where the "Board" button should appear. If left blank, it will be shown everywhere. Use @ to denote the top level view.
display_modes:
  type: list
  default: ""
  description:
    en: "Override the default board display mode for each category/tag. Use the syntax `category:mode:params`/`tag:mode:params`. For example, `support:assigned:david,sam,joffrey`. Use @ to denote the top level view. Use @untagged to display an untagged column. Use $ to enter a single default mode for ALL boards, for example, `$:tags:doing,done`"
require_confirmation:
  default: true
  description:
    en: Display a confirmation modal before making changes to a topic's tags/category?
show_tags:
  default: false
  description:
    en: Show tags on topic cards?
extra_icons:
  default: "user-minus"
  description:
    en: Extra icons to load for the theme component. There is no need to change this setting.
